### ISSUE TITLE
Upgrade SeNginx to the latest Nginx

### ISSUE THREAD

**Issue by tanviet12** [cuper6/SEnginx#2]
Hello,

Thank you for maintaining SeNginx.  Currently SeNginx is using Nginx 1.18.0 (21 Apr 2020), it's very old. Can you upgrade it to the latest Nginx version (nginx-1.20.2)?

Thanks very much!

**Comment by cuper6** [comment]
SEnginx is security focused. That is why I do not chase for the latest “hot” nginx where some bugs or security holes may exist. 
My policy is to upgrade Senginx to the stable nginx-1 version. Currently this is 1.18. By the way TEngine also based on nginx 1.18 now.
The latest stable nginx 1.20.2 was released only 4 months ago (2021-11-16).
What new features of nginx 1.20 you consider as important for SEnginx?

**Comment by cuper6** [comment]
senginx Pro 1.10.1 has nginx 1.22.0 ''on board".
http://senginx.ru/
